---
name: ExampleOS
actions:
  bootstrap:
    suite: trixie
    target: rootfs
    components: [main, contrib, non-free, non-free-firmware]

    # Customizations that happen before bootstrapping.
    setup-hooks:
      - 'sync-in overlay/debian/ /'
    
    # Customizations that happen after boostrapping.
    customize-hooks:
      - 'sync-in overlay/adduser/ /'
      - echo 'root:root' | chroot "$1" chpasswd
      - chroot $1 echo "localhost" > $1/etc/hostname
      - systemctl disable --root=$1 apt-daily.timer cron
      - chroot $1 cp -alf /lib/systemd/resolv.conf /etc/resolv.conf
    
    # Packages to install after bootstrapping.
    packages:
      - linux-image-amd64
      - firmware-linux
      - sudo
      - systemd-boot
      - dracut
      - vim
      - net-tools
      - openssh-client
      - openssh-server
      - procps
      - less
      - dbus
      - policykit-1
      - libnss-resolve
      - libnss-systemd
